theme: jekyll-theme-modernist
markdown: kramdown
domainUrl: "https://georgedavis-tm.github.io"
baseUrl: ""
exclude: ['README.md']
permalink: pretty
title: GeorgeDavis-TM
description: Project work of George Davis
twitter_username: GDCrocx

#Hosting settings
port: 80